; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
include_dir = .

[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
build_src_filter = +<*> -<.git/> -<.svn/> -<ch32fun/>
framework = ch32v003fun
; use exact ch32fun repo version that's referenced in this project to keep it stable
platform_packages = 
    framework-ch32v003fun@symlink://ch32fun

[base_v003]
board = genericCH32V003F4U6
; needed so that we don't get misidentified as a CH32V00{2,4,5,6} or CH32M.
build_unflags = -DCH32V00x

[base_103]
build_flags = -DCH32V10x
board = genericCH32V103C8T6

[base_203]
build_flags = -DCH32V20x
board = genericCH32V203C8T6

[base_307]
build_flags = -DCH32V30x
board = ch32v307_evt

[base_x035]
build_flags = -DCH32X03x -std=gnu11
build_unflags = -std=gnu99
board = genericCH32X035C8T6

[base_5xx]
build_flags = -DCH5xx -std=gnu11
build_unflags = -std=gnu99
; select the exact chip here!
;board = genericCH570D
;board = genericCH572Q
;board = genericCH573F
board = genericCH582F
;board = genericCH592X

[base_h41x]
; for a yet unknown reason, firmware does not work with -msave-restore. disable it.
build_flags = -DCH32H417 -DDISABLED_FLOAT -std=gnu11 -mno-save-restore
build_unflags = -std=gnu99 -msave-restore
; for floating point support, comment above build_flags and uncomment these 
;build_flags =  -DCH32H417 -std=gnu11  -mno-save-restore
;board_build.march = rv32imafc_zba_zbb_zbc_zbs_xw
;board_build.mabi = ilp32f

[env:my_blink]
; extend the correct environment if the project is based on ch32v003, 103, 203, etc.
extends = base_v003